### PR TITLE
testnet label and network logo fixes

### LINKED ISSUE #3147: testnet label fixes
- desktop horizontal navigation: remove fixed logo width so there's no additional margin between logo and testnet label when logo's width is less than 120px
- mobile navigation drawer: add bottom margin to the testnet label
- mobile header: for testnets use icon instead of the logo and add testnet label

### PR DESCRIPTION
**Pull request by isstuev**
## Description and Related Issue(s)

fixes #3147 

### Additional Information
Also I refactored NetworkLogo component since it was a bit overengineered 

## Checklist for PR author
- [ ] I have tested these changes locally.
- [ ] I added tests to cover any new functionality, following this [guide](./CONTRIBUTING.md#writing--running-tests)
- [ ] Whenever I fix a bug, I include a regression test to ensure that the bug does not reappear silently.
- [ ] If I have added, changed, renamed, or removed an environment variable
    - I updated the list of environment variables in the [documentation](ENVS.md) 
    - I made the necessary changes to the validator script according to the [guide](./CONTRIBUTING.md#adding-new-env-variable)
    - I added "ENVs" label to this pull request

### CODE REVIEW

File: toolkit/chakra/image.tsx [hunk 1]
```diff
@@ -6,11 +6,14 @@ import { Skeleton } from './skeleton';
 
 export interface ImageProps extends ChakraImageProps {
   fallback?: React.ReactNode;
+  // for the case where the image dimensions are not known before the image is loaded
+  skeletonWidth?: BoxProps['width'];
+  skeletonHeight?: BoxProps['height'];
```
Comment (tom2drum) [inline toolkit/chakra/image.tsx:11]: Since `skeletonWidth` without `skeletonHeight` doesn't make much sense (if I understand the comment correctly), it may be better to combine these props into a single object.


```suggestion
  // for the case where the image dimensions are not known before the image is loaded
  skeletonProps?: BoxProps;
```

Comment (isstuev) [reply toolkit/chakra/image.tsx:11]: skeleton props are inherited from the component props, but can be overwritten by those -- I think it's clearer what are they for in case of width/height, not just generic 'props'
